<?php

namespace App\Actions\PartsList;

use App\Models\PartList;

class PartsListDefaultAction
{
    private const DEFAULT_PDR = [
        [
          'parent_id' => 0,
          'item_name_eng' => 'ENGINE WITH GEARBOX',
          'item_name_ru' => '',
          'is_folder' => 1,
          'children' => [],
        ],
        [
          'parent_id' => 0,
          'item_name_eng' => 'ENGINE',
          'item_name_ru' => '',
          'is_folder' => 1,
          'children' => [
              [
                  'parent_id' => 0,
                  'item_name_eng' => 'ENGINE, ASSY',
                  'item_name_ru' => '',
                  'is_folder' => 1,
                  'children' => [
                      [
                          'parent_id' => 0,
                          'item_name_eng' => 'THROTTLE BODY',
                          'item_name_ru' => '',
                          'is_folder' => 0,
                          'children' => [],
                      ],
                      [
                          'parent_id' => 0,
                          'item_name_eng' => 'ALTERNATOR',
                          'item_name_ru' => '',
                          'is_folder' => 0,
                          'children' => [],
                      ],
                      [
                          'parent_id' => 0,
                          'item_name_eng' => 'STARTER MOTOR',
                          'item_name_ru' => '',
                          'is_folder' => 0,
                          'children' => [],
                      ],
                      [
                          'parent_id' => 0,
                          'item_name_eng' => 'INTERCOOLER',
                          'item_name_ru' => '',
                          'is_folder' => 0,
                          'children' => [],
                      ],
                 ],
              ],
          ],
        ],
        [
          'parent_id' => 0,
          'item_name_eng' => 'TRANS/GEARBOX',
          'item_name_ru' => '',
          'is_folder' => 1,
          'children' => [
                  [
                      'parent_id' => 0,
                      'item_name_eng' => 'TRANS/GEARBOX',
                      'item_name_ru' => '',
                      'is_folder' => 0,
                      'children' => []
                  ],
                  [
                      'parent_id' => 0,
                      'item_name_eng' => 'DIFFERENTIAL CENTRE',
                      'item_name_ru' => '',
                      'is_folder' => 0,
                      'children' => []

                  ],
                  [
                      'parent_id' => 0,
                      'item_name_eng' => 'FRONT DIFF ASSEMBLY',
                      'item_name_ru' => '',
                      'is_folder' => 0,
                      'children' => []
                  ],
                  [
                      'parent_id' => 0,
                      'item_name_eng' => 'REAR DIFF ASSEMBLY',
                      'item_name_ru' => '',
                      'is_folder' => 0,
                      'children' => []
                  ],
              ],
          ],
          [
            'parent_id' => 0,
            'item_name_eng' => 'FRONT END ASSY',
            'item_name_ru' => '',
            'is_folder' => 1,
            'children' => [],
          ],
          [
            'parent_id' => 0,
            'item_name_eng' => 'FRONT BUMPER',
            'item_name_ru' => '',
            'is_folder' => 1,
            'children' => [
                [
                    'parent_id' => 0,
                    'item_name_eng' => 'LEFT INDICATOR/FOG/SIDE',
                    'item_name_ru' => '',
                    'is_folder' => 0,
                    'children' => [],
                ],
                [
                    'parent_id' => 0,
                    'item_name_eng' => 'RIGHT INDICATOR/FOG/SIDE',
                    'item_name_ru' => '',
                    'is_folder' => 0,
                    'children' => []
                ],
            ],
          ],
          [
            'parent_id' => 0,
            'item_name_eng' => 'LEFT HEADLAMP',
            'item_name_ru' => '',
            'is_folder' => 0,
            'children' => [],
          ],
          [
            'parent_id' => 0,
            'item_name_eng' => 'RIGHT HEADLAMP',
            'item_name_ru' => '',
            'is_folder' => 0,
            'children' => [],
          ],
          [
            'parent_id' => 0,
            'item_name_eng' => 'GRILLE',
            'item_name_ru' => '',
            'is_folder' => 0,
            'children' => [],
          ],
          [
            'parent_id' => 0,
            'item_name_eng' => 'FRONT BAR BRKT/REINFORCEMENT',
            'item_name_ru' => '',
            'is_folder' => 0,
            'children' => [],
          ],
          [
            'parent_id' => 0,
            'item_name_eng' => 'RADIATOR SUPPORT',
            'item_name_ru' => '',
            'is_folder' => 0,
            'children' => [],
          ],
          [
            'parent_id' => 0,
            'item_name_eng' => 'RADIATOR',
            'item_name_ru' => '',
            'is_folder' => 0,
            'children' => [],
          ],
          [
            'parent_id' => 0,
            'item_name_eng' => 'A/C CONDENSER',
            'item_name_ru' => '',
            'is_folder' => 1,
            'children' => [
                    [
                        'parent_id' => 0,
                        'item_name_eng' => 'A/C HOSES',
                        'item_name_ru' => '',
                        'is_folder' => 0,
                    ],
                ],
          ],
          [
            'parent_id' => 0,
            'item_name_eng' => 'OVERFLOW BOTTLE',
            'item_name_ru' => '',
            'is_folder' => 0,
            'children' => [],
          ],
          [
            'parent_id' => 0,
            'item_name_eng' => 'BONNET',
            'item_name_ru' => '',
            'is_folder' => 1,
            'children' => [
                [
                    'parent_id' => 0,
                    'item_name_eng' => 'BONNET HINGE/STRUT',
                    'item_name_ru' => '',
                    'is_folder' => 0,
                    'children' => [],
                ],
                [
                    'parent_id' => 0,
                    'item_name_eng' => 'BONNET LOCK/SUPPORT',
                    'item_name_ru' => '',
                    'is_folder' => 0,
                    'children' => [],
                ],
            ]
        ],
        [
            'parent_id' => 0,
            'item_name_eng' => 'LEFT GUARD',
            'item_name_ru' => '',
            'is_folder' => 0,
            'children' => [],
        ],
        [
            'parent_id' => 0,
            'item_name_eng' => 'LEFT GUARD LINER',
            'item_name_ru' => '',
            'is_folder' => 0,
            'children' => [],
        ],
        [
            'parent_id' => 0,
            'item_name_eng' => 'RIGHT GUARD',
            'item_name_ru' => '',
            'is_folder' => 0,
            'children' => [],
        ],
        [
            'parent_id' => 0,
            'item_name_eng' => 'RIGHT GUARD LINER',
            'item_name_ru' => '',
            'is_folder' => 0,
            'children' => [],
        ],
        [
            'parent_id' => 0,
            'item_name_eng' => 'LEFT FRONT DOOR',
            'item_name_ru' => '',
            'is_folder' => 1,
            'children' => [
                [
                    'parent_id' => 0,
                    'item_name_eng' => 'DOOR HINGE/RUNNER',
                    'item_name_ru' => '',
                    'is_folder' => 0,
                    'children' => [],
                ],
                [
                    'parent_id' => 0,
                    'item_name_eng' => 'DOOR TRIM',
                    'item_name_ru' => '',
                    'is_folder' => 0,
                    'children' => [],
                ],
                [
                    'parent_id' => 0,
                    'item_name_eng' => 'LEFT FRONT WINDOW REG/MOTOR',
                    'item_name_ru' => '',
                    'is_folder' => 0,
                    'children' => [],
                ],
                [
                    'parent_id' => 0,
                    'item_name_eng' => 'LEFT FRONT DOOR WINDOW',
                    'item_name_ru' => '',
                    'is_folder' => 0,
                    'children' => [],
                ],
                [
                    'parent_id' => 0,
                    'item_name_eng' => 'LEFT FRONT 1/4 DOOR GLASS',
                    'item_name_ru' => '',
                    'is_folder' => 0,
                    'children' => [],
                ],
                [
                    'parent_id' => 0,
                    'item_name_eng' => 'DOOR HANDLE',
                    'item_name_ru' => '',
                    'is_folder' => 0,
                    'children' => [],
                ],
                [
                    'parent_id' => 0,
                    'item_name_eng' => 'POWER WINDOW SWITCH',
                    'item_name_ru' => '',
                    'is_folder' => 0,
                    'children' => [],
                ],
            ],
        ],
        [
            'parent_id' => 0,
            'item_name_eng' => 'LEFT DOOR MIRROR',
            'item_name_ru' => '',
            'is_folder' => 0,
            'children' => [],
        ],
        [
            'parent_id' => 0,
            'item_name_eng' => 'RIGHT FRONT DOOR',
            'item_name_ru' => '',
            'is_folder' => 1,
            'children' => [
                [
                    'parent_id' => 0,
                    'item_name_eng' => 'DOOR HINGE/RUNNER',
                    'item_name_ru' => '',
                    'is_folder' => 0,
                    'children' => [],
                ],
                [
                    'parent_id' => 0,
                    'item_name_eng' => 'DOOR TRIM',
                    'item_name_ru' => '',
                    'is_folder' => 0,
                    'children' => [],
                ],
                [
                    'parent_id' => 0,
                    'item_name_eng' => 'POWER WINDOW SWITCH',
                    'item_name_ru' => '',
                    'is_folder' => 0,
                    'children' => [],
                ],
                [
                    'parent_id' => 0,
                    'item_name_eng' => 'RIGHT FRONT DOOR WINDOW',
                    'item_name_ru' => '',
                    'is_folder' => 0,
                    'children' => [],
                ],
                [
                    'parent_id' => 0,
                    'item_name_eng' => 'RIGHT FRONT 1/4 DOOR GLASS',
                    'item_name_ru' => '',
                    'is_folder' => 0,
                    'children' => [],
                ],
                [
                    'parent_id' => 0,
                    'item_name_eng' => 'DOOR HANDLE',
                    'item_name_ru' => '',
                    'is_folder' => 0,
                    'children' => [],
                ],
                [
                    'parent_id' => 0,
                    'item_name_eng' => 'RIGHT FRONT WINDOW REG/MOTOR',
                    'item_name_ru' => '',
                    'is_folder' => 0,
                    'children' => [],
                ],
                [
                    'parent_id' => 0,
                    'item_name_eng' => 'COMBINATION SWITCH',
                    'item_name_ru' => '',
                    'is_folder' => 0,
                    'children' => [],
                ],
            ],
        ],
        [
            'parent_id' => 0,
            'item_name_eng' => 'RIGHT DOOR MIRROR',
            'item_name_ru' => '',
            'is_folder' => 0,
            'children' => [],
        ],
        [
            'parent_id' => 0,
            'item_name_eng' => 'LEFT REAR DOOR',
            'item_name_ru' => '',
            'is_folder' => 1,
            'children' => [
                [
                    'parent_id' => 0,
                    'item_name_eng' => 'DOOR HINGE/RUNNER',
                    'item_name_ru' => '',
                    'is_folder' => 0,
                    'children' => [],
                ],
                [
                    'parent_id' => 0,
                    'item_name_eng' => 'LEFT REAR 1/4 DOOR GLASS',
                    'item_name_ru' => '',
                    'is_folder' => 0,
                    'children' => [],
                ],
                [
                    'parent_id' => 0,
                    'item_name_eng' => 'LEFT REAR DOOR WINDOW',
                    'item_name_ru' => '',
                    'is_folder' => 0,
                    'children' => [],
                ],
                [
                    'parent_id' => 0,
                    'item_name_eng' => 'DOOR TRIM',
                    'item_name_ru' => '',
                    'is_folder' => 0,
                    'children' => [],
                ],
                [
                    'parent_id' => 0,
                    'item_name_eng' => 'DOOR HANDLE',
                    'item_name_ru' => '',
                    'is_folder' => 0,
                    'children' => [],
                ],
                [
                    'parent_id' => 0,
                    'item_name_eng' => 'LEFT REAR WND REG/MOTOR',
                    'item_name_ru' => '',
                    'is_folder' => 0,
                    'children' => [],
                ],
                [
                    'parent_id' => 0,
                    'item_name_eng' => 'POWER WINDOW SWITCH',
                    'item_name_ru' => '',
                    'is_folder' => 0,
                    'children' => [],
                ],
            ],
        ],
        [
            'parent_id' => 0,
            'item_name_eng' => 'RIGHT REAR DOOR',
            'item_name_ru' => '',
            'is_folder' => 1,
            'children' => [
                [
                    'parent_id' => 0,
                    'item_name_eng' => 'DOOR HINGE/RUNNER',
                    'item_name_ru' => '',
                    'is_folder' => 0,
                    'children' => [],
                ],
                [
                    'parent_id' => 0,
                    'item_name_eng' => 'RIGHT REAR 1/4 DOOR GLASS',
                    'item_name_ru' => '',
                    'is_folder' => 0,
                    'children' => [],
                ],
                [
                    'parent_id' => 0,
                    'item_name_eng' => 'RIGHT REAR DOOR WINDOW',
                    'item_name_ru' => '',
                    'is_folder' => 0,
                    'children' => [],
                ],
                [
                    'parent_id' => 0,
                    'item_name_eng' => 'DOOR TRIM',
                    'item_name_ru' => '',
                    'is_folder' => 0,
                    'children' => [],
                ],
                [
                    'parent_id' => 0,
                    'item_name_eng' => 'DOOR HANDLE',
                    'item_name_ru' => '',
                    'is_folder' => 0,
                    'children' => [],
                ],
                [
                    'parent_id' => 0,
                    'item_name_eng' => 'RIGHT REAR WND REG/MOTOR',
                    'item_name_ru' => '',
                    'is_folder' => 0,
                    'children' => [],
                ],
                [
                    'parent_id' => 0,
                    'item_name_eng' => 'POWER WINDOW SWITCH',
                    'item_name_ru' => '',
                    'is_folder' => 0,
                    'children' => [],
                ],
            ],
        ],
        [
            'parent_id' => 0,
            'item_name_eng' => 'BOOTLID/TAILGATE',
            'item_name_ru' => '',
            'is_folder' => 1,
            'children' => [
               [
                    'parent_id' => 0,
                    'item_name_eng' => 'BOOTLID/TGATE HINGE',
                    'item_name_ru' => '',
                    'is_folder' => 0,
                    'children' => [],
               ],
               [
                    'parent_id' => 0,
                    'item_name_eng' => 'REAR/TAILGATE GLASS',
                    'item_name_ru' => '',
                    'is_folder' => 0,
                    'children' => [],
               ],
                [
                    'parent_id' => 0,
                    'item_name_eng' => 'TAILGATE HANDLE',
                    'item_name_ru' => '',
                    'is_folder' => 0,
                    'children' => [],
                ],
            ]
        ],
        [
            'parent_id' => 0,
            'item_name_eng' => 'REAR BUMPER',
            'item_name_ru' => '',
            'is_folder' => 0,
            'children' => [],
        ],
        [
            'parent_id' => 0,
            'item_name_eng' => 'REAR BAR BRKT/REINFORCEMENT',
            'item_name_ru' => '',
            'is_folder' => 0,
            'children' => [],
        ],
        [
            'parent_id' => 0,
            'item_name_eng' => 'LEFT TAILLIGHT',
            'item_name_ru' => '',
            'is_folder' => 0,
            'children' => [],
        ],
        [
            'parent_id' => 0,
            'item_name_eng' => 'RIGHT TAILLIGHT',
            'item_name_ru' => '',
            'is_folder' => 1,
            'children' => [
                [
                    'parent_id' => 0,
                    'item_name_eng' => 'WIPER LINKAGE',
                    'item_name_ru' => '',
                    'is_folder' => 0,
                    'children' => [],
                ],
                [
                    'parent_id' => 0,
                    'item_name_eng' => 'WIPER ARM',
                    'item_name_ru' => '',
                    'is_folder' => 0,
                    'children' => [],
                ],
            ],
        ],
        [
            'parent_id' => 0,
            'item_name_eng' => 'OTHER',
            'item_name_ru' => '',
            'is_folder' => 1,
            'children' => [
                [
                    'parent_id' => 0,
                    'item_name_eng' => 'OTHER EXTERIOR',
                    'item_name_ru' => '',
                    'is_folder' => 1,
                    'children' => [
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'FUEL DOOR / FILLER',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'HIGH LEVEL STOPLIGHT',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'REVERSING LIGHT',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'WHEEL ARCH FLARE',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'HATCH STRUT',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'REAR SPOILER',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'TOWBAR',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'RIGHT QUARTER PANEL',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'BODY SEAL RUBBER',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'ANTENNA',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'BODY/DOOR MOULD',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'FRONT SPOILER',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'SIDE STEP/SKIRT',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'WHEEL ALLOY',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'REAR SECTION',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'REAR GARNISH',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'NUMBER PLATE LAMP',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'MUD FLAPS',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'WHEEL STEEL',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'WHEEL COVER/HUB CAP',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'WINDSCREEN',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'REAR/TAILGATE GLASS',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'LEFT REAR SIDE GLASS',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'RIGHT REAR SIDE GLASS',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'ROOF GLASS/SUNROOF/T',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'LEFT SIDE CUT SECTION',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                    ],
                ],
                [
                    'parent_id' => 0,
                    'item_name_eng' => 'INTERIOR',
                    'item_name_ru' => '',
                    'is_folder' => 1,
                    'children' => [
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'STEREO/HEAD UNIT',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'WIPER SWITCH',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'WIPER MOTOR',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'HEATER FAN MOTOR',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'HEATER/AC CONTROLS',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'COURTESY LIGHT',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'GLOVE BOX',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'FRONT SEAT',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => '2ND SEAT (REAR SEAT)',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => '3RD SEAT',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'SEAT BELT',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'TRIM PANEL',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'DASH ASSEMBLY',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'PEDAL ASSEMBLY',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'CONSOLE',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'ARMREST',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'HEADREST',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'INTERIOR MIRROR',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'SUN VISOR',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'IGNITION W/ KEY',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'PARCEL SHELF',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'LOCK MECHANISM',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'TRIM PANEL',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                    ],
                ],
                [
                    'parent_id' => 0,
                    'item_name_eng' => 'FRONT SUSPENSION',
                    'item_name_ru' => '',
                    'is_folder' => 1,
                    'children' => [
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'LEFT FRONT STRUT',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'RIGHT FRONT STRUT',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'LEFT FRONT LOWER CONTROL ARM',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'RIGHT FRONT LOWER CONTROL ARM',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'LEFT FRONT UPPER CONTROL ARM',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'RIGHT FRONT UPPER CONTROL ARM',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'LEFT DRIVESHAFT',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'RIGHT DRIVESHAFT',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'LEFT FRONT HUB ASSEMBLY',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'RIGHT FRONT HUB ASSEMBLY',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'STABILIZER BAR',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'FRT XMEMBER/CRADLE',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                    ],
                ],
                [
                    'parent_id' => 0,
                    'item_name_eng' => 'REAR SUSPENSION',
                    'item_name_ru' => '',
                    'is_folder' => 1,
                    'children' => [
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'SHOCK ABSORBER, LR',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'SHOCK ABSORBER, RR',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'LEFT REAR STRUT',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'RIGHT REAR STRUT',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'LEFT REAR TRAILING ARM',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'RIGHT REAR TRAILING ARM',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'LEFT REAR HUB ASSEMBLY',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'RIGHT REAR HUB ASSEMBLY',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'REAR AXLE BEAM (FWD)',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'AXLE',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'REAR AXLE BEAM (FWD)',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                    ],
                ],
                [
                    'parent_id' => 0,
                    'item_name_eng' => 'BRAKE SYSTEM',
                    'item_name_ru' => '',
                    'is_folder' => 1,
                    'children' => [
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'MASTER CYLINDER',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'CALIPER',
                            'item_name_ru' => '',
                            'is_folder' => 1,
                            'children' => [
                                [
                                    'parent_id' => 0,
                                    'item_name_eng' => 'CALIPER, LH FRONT',
                                    'item_name_ru' => '',
                                    'is_folder' => 0,
                                    'children' => [],
                                ],
                                [
                                    'parent_id' => 0,
                                    'item_name_eng' => 'CALIPER, RH FRONT',
                                    'item_name_ru' => '',
                                    'is_folder' => 0,
                                    'children' => [],
                                ],
                                [
                                    'parent_id' => 0,
                                    'item_name_eng' => 'CALIPER, LH REAR',
                                    'item_name_ru' => '',
                                    'is_folder' => 0,
                                    'children' => [],
                                ],
                                [
                                    'parent_id' => 0,
                                    'item_name_eng' => 'CALIPER, RH REAR',
                                    'item_name_ru' => '',
                                    'is_folder' => 0,
                                    'children' => [],
                                ],
                            ],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'FRONT BRAKE DISC',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'ABS PUMP/MODULATOR',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'ABS SENSOR',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                    ],
                ],
                [
                    'parent_id' => 0,
                    'item_name_eng' => 'STEERING',
                    'item_name_ru' => '',
                    'is_folder' => 1,
                    'children' => [
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'STEERING COLUMN',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'STEERING WHEEL',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'POWER STEER HOSE',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'STEERING BOX/RACK',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'STEERING PUMP',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'STEERING COLUMN SHRO',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'STEERING KNUCKLE',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                    ],
                ],
                [
                    'parent_id' => 0,
                    'item_name_eng' => 'OTHER ',
                    'item_name_ru' => '',
                    'is_folder' => 1,
                    'children' => [
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'AIR FLOW METER',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'DRAG LINK',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'JACK',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'INSTRUMENT CLUSTER',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'OXYGEN SENSOR',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'A/C REFRIGERANT',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'INVERTER',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'MUFFLER',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'WATER PIPES/OUTLETS',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'FAN',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'OIL FILTER/HOUSING',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'HIGH VOLTAGE BATTERY',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'FRONT BULKHEAD',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'TONNEAU/COVER',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'FAN SHROUD',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'THERMOSTAT HOUSING',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'AIRBAG MODULE/SENSOR',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'FUSE BOX',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'WASHER BOTTLE',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'BATTERY',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'MANIFOLD',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'LOWER ENGINE SPLASH TRAY',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'EXHAUST SYSTEM',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'TAIL PIPE',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'AIR CLEANER/BOX',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'AIR CLEANER DUCT/HOS',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'CRANKSHAFT',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'CRANKSHAFT PULLEY',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'FUEL PUMP',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'FUEL SENDING UNIT',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'CATALYTIC CONVERTER',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'EGR VALVE',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'COIL/COIL PACK',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'ECU',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'CYLINDER HEAD',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'MOUNT',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'WIPER LINKAGE',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                        [
                            'parent_id' => 0,
                            'item_name_eng' => 'WIPER ARM',
                            'item_name_ru' => '',
                            'is_folder' => 0,
                            'children' => [],
                        ],
                    ],
                ],
            ],
        ],
    ];

    public function handle(): array
    {
        $list = PartList::all();
        if (!$list->count()) {
            $this->createDefaultList(self::DEFAULT_PDR);
            $list = PartList::all();
        }

        return $this->loadDefaultList($list->toArray());
    }

    private function createDefaultList(array $elements, $parentId = 0): void
    {
        foreach ($elements as $el) {
            if (isset($el['children']) && count($el['children'])) {
                $el['icon'] = 'pi pi-pw pi-folder';
            } else {
                $el['icon'] = 'pi pi-fw pi-cog';
            }

            $part = PartList::create([
                    'parent_id' => $parentId,
                    'item_name_eng' => $el['item_name_eng'],
                    'item_name_ru' => $el['item_name_ru'],
                    'is_folder' => $el['is_folder'],
                    'is_virtual' => false,
                    'icon_name' => $el['icon'],
                    'key' => null,
                    'is_used' => true
                ]);

            $el['key'] = $el['parent_id'] . '-'. $part->id;
            $part->update(['key' => $el['key']]);

            if (isset($el['children']) && count($el['children'])) {
                $this->createDefaultList($el['children'], $part->id);
            }
        }
    }

    private function loadDefaultList(array $elements, $parentId = 0): array
    {
        $branch = [];
        foreach ($elements as $el) {
            if ($el['parent_id'] === $parentId) {
                $children = $this->loadDefaultList($elements, $el['id']);
                if (count($children)) {
                    $el['children'] = $children;
                }
                $el['icon'] = $el['icon_name'];
                $branch[] = $el;
            }
        }
        return $branch;
    }
}
